Repository condinoaljoseph/meaningful, pull requests merged in 2022-10, with the labels that each got.

#33 Add loading spinner component
  vermar/src/components/Login.tsx
  vermar/src/components/NavbarAccount.tsx
  vermar/src/components/ui/Button.tsx
  vermar/src/components/ui/LoadingSpinner.tsx
  vermar/src/styles/globals.css
  vermar/src/styles/loading.css
Labels: hacktoberfest-accepted

#35 Use lower version of typeorm and add paginated posts
  dern/package.json
  dern/src/data-source.ts
  dern/src/entities/Post.ts
  dern/src/index.ts
  dern/src/resolvers/hello.ts
  dern/src/resolvers/post.ts
  dern/src/resolvers/reaction.ts
  dern/src/resolvers/user.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#40 Add ssr support for home page and post pages
  vermar/package.json
  vermar/src/components/ButtonMore.tsx
  vermar/src/components/ButtonShare.tsx
  vermar/src/components/Layout.tsx
  vermar/src/components/NavbarAccount.tsx
  vermar/src/components/ui/Markdown.tsx
  vermar/src/components/ui/MenuAccount.tsx
  vermar/src/pages/[u]/[id]/edit.tsx
  vermar/src/pages/[u]/[id]/index.tsx
  vermar/src/pages/[u]/index.tsx
  vermar/src/pages/_app.tsx
  vermar/src/pages/index.tsx
  vermar/src/pages/new.tsx
  vermar/src/store/useAppStore.ts
  vermar/src/utils/withApollo.tsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#50 Add popover when hovering to user on post items
  vermar/package.json
  vermar/src/components/ButtonMore.tsx
  vermar/src/components/ButtonShare.tsx
  vermar/src/components/PostsItem.tsx
  vermar/src/components/UserPophover.tsx
  vermar/src/components/ui/MenuAccount.tsx
  vermar/src/generated/graphql.tsx
  vermar/src/graphql/fragments/PostFragment.graphql
  vermar/src/graphql/fragments/UserFragment.graphql
  vermar/src/graphql/mutations/login.graphql
  vermar/src/graphql/queries/me.graphql
  vermar/src/graphql/queries/post.graphql
  vermar/src/graphql/queries/user.graphql
  vermar/src/pages/[u]/[id]/index.tsx
  yarn.lock
Labels: enhancement

#55 cache and batch request using dataloaders
  dern/package.json
  dern/src/index.ts
  dern/src/resolvers/post.ts
  dern/src/types.ts
  dern/src/utils/createReactionLoader.ts
  dern/src/utils/createUserLoader.ts
  vermar/src/components/ButtonReact.tsx
  vermar/src/components/ButtonShare.tsx
  vermar/src/components/FlashNotifications.tsx
  vermar/src/components/Login.tsx
  vermar/src/components/ui/MenuAccount.tsx
  vermar/src/pages/[u]/[id]/edit.tsx
  vermar/src/pages/[u]/[id]/index.tsx
  vermar/src/pages/new.tsx
  yarn.lock
Labels: enhancement

#57 Prevent layout shifts on mobile editor previews
  vermar/src/pages/[u]/[id]/edit.tsx
  vermar/src/pages/new.tsx
Labels: hacktoberfest-accepted

#59 Fix for layout breaking on mobile when side navigation is open
  vermar/src/components/Layout.tsx
Labels: hacktoberfest-accepted

#60 use github oauth
  dern/.env.example
  dern/.gitignore
  dern/ormconfig.json
  dern/package.json
  dern/src/entities/User.ts
  dern/src/env.d.ts
  dern/src/index.ts
  dern/src/migrations/1665521007153-MockPosts.ts
  dern/src/migrations/1667213662696-UserRefactoring.ts
  dern/src/resolvers/user.ts
  vermar/src/components/Login.tsx
  vermar/src/components/NavbarAccount.tsx
  vermar/src/components/UserPophover.tsx
  vermar/src/components/ui/AvatarUser.tsx
  vermar/src/generated/graphql.tsx
  vermar/src/graphql/fragments/UserFragment.graphql
  vermar/src/graphql/mutations/login.graphql
  vermar/src/pages/[u]/[id]/index.tsx
  vermar/src/pages/[u]/index.tsx
  yarn.lock
Labels: enhancement
